### ISSUE TITLE
Instructions for accessing the development tools 

### ISSUE THREAD

**Issue by cakenggt** [kesiev/rewtro#1]
Regarding the development tools screenshotted in the README, I attempted to load up the url https://www.kesiev.com/rewtro/carts since that index.html file is where the dev tools seem to be, but I am getting a 404 whenever I navigate to that url. What would the correct way be to access the dev tools?

**Comment by kesiev** [comment]
Well. I didn't publish the SDK part on kesiev.com since you've to create your own development environment on your own machine in order to make a game: you need an Apache server with PHP support and a text editor to change the files under the `carts/` directory.

No writing access to the `carts/` folder makes it not very useful but... I decided to publish the SDK folder right now anyway, so you can have a preview of the (very few) development tools and have a look to the demo games using the debugger. :)

I'll update the README.md with further instructions. Thanks!

**Comment by cakenggt** [comment]
Thanks! Is it in the spirit of the project to eventually include editing tools that can create new cartridges and do something like save them to localstorage, or include download/upload of the json files for the ability to continuously develop a game using just the web interface? I'm thinking of something along the lines of https://script-8.github.io/ in terms of editing ability, obviously without the backend server sending a list of games.

**Comment by kesiev** [comment]
Wow! Very nice and inspiring project and the localstorage idea is good!

There is a world of easier fantasy consoles out there so, for Rewtro, I'd like to keep the "old-school background story" I've thought around the project, even if it's not practical. So: few commands that looks like _enhanced low-level operations_, local offline SDK, so you own all the software, and self-printing the cartridge like you own a hardware factory.

Anyway you're right: there is a whole lot of stuff that's missing in order to make Rewtro anything like a true project - first of all probably it's missing a developer manual or coding guide. Sadly it's a pet project I'm working on alone and I've another full time job, so I'll try to make the SDK better in my spare time - waiting for some kind of help.

**Comment by JohnEarnest** [comment]
I've also built a browser-based game development environment based around the venerable CHIP-8 virtual machine. Might offer some useful ideas when/if you get around to fleshing out your dev tools: https://github.com/JohnEarnest/Octo
